VIR-192 Also Delete Rule definitions when deleting a field.
Govexec/django-formulaic pull request #39
Opened 2023-03-27 16:57 UTC by LachieBell

This ticket fixes a previous bug introduced when trying to make the interface more forgiving. This is still a work around, but it is a better workaround. The doc string for the function is still valid.

Now when a Field attempts to be deleted, we also check to see if it had any related rule results or rule conditions. If for a given Rule, it was the last rule result or rule condition, we also delete the Rule. 

This could still lead to problems down the line, and is not a the best solution. But it is a better solution for right now.

2023-03-27 19:28 UTC, isasiluispy requested changes

2023-03-29 11:06 UTC, levimoore1992 requested changes
If you can add some unit tests please.This feature can get broken easily as we work more on formulaic so we need to rock solid that everything we work on in the future works

2023-03-29 16:40 UTC, LachieBell commented
> If you can add some unit tests please.This feature can get broken easily as we work more on formulaic so we need to rock solid that everything we work on in the future works

Sure, added.

2023-03-29 16:40 UTC, LachieBell commented on formulaic/views.py
> +        models.RuleCondition.objects.filter(id__in=rule_conditions_ids_to_be_delete).delete()
Good catch. It's a good idea. Thanks, I've added it in.

2023-04-03 13:33 UTC, isasiluispy approved these changes

2023-04-03 16:07 UTC, merged